name: Document

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  document:
    name: Generate docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: cogna-dev/moonbit-actions/setup@v0

      - name: Generate documentation
        uses: cogna/moonbit-actions/document@v0
